name: sample
on:
  push:

  # Run the job only with "docs_changed" equals "True"
  conditional_job:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/conditional-job-reusable.yml
    needs: [ conditional_job_check_files ]
    if: needs.conditional_job_check_files.outputs.docs_changed == 'True'
    steps:
      - shell: pwsh
        run: echo publish docs