name: sample
on:
  push:

  # Run the job only with "docs_changed" equals "True"
jobs:
  job1:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/conditional-job-reusable.yml

  conditional_job:
    runs-on: ubuntu-latest
    needs: [ job1 ]
    if: needs.job1.outputs.docs_changed == 'True'
    steps:
     - run: echo "hurray...publish docs"