name: sample
on:
  push:

  # Run the job only with "docs_changed" equals "True"
jobs:
  job1:
    uses: ./.github/workflows/conditional-job-reusable.yml
    with:
      targetBranch: master
      package: '^src/main/frontend/'

  conditional_job:
    runs-on: ubuntu-latest
    needs: [ job1 ]
    if: needs.job1.outputs.workflowOutput == 'True'
    steps:
     - run: echo "hurray...publish docs"